site_name: Kenny Writes
site_description: The blog of Kenny Robinson, where he shares is hobbies and other thoughts.
site_url: https://almostengr.github.io/
site_author: Kenny Robinson, @almostengr

# deployment branch details
remote_branch: master
remote_name: origin

theme:
  name: null
  custom_dir: blogalmostengr

copyright: Copyright &copy; 2015-2020 Kenny Robinson

# Development server details
dev_addr: 192.168.57.117:8000

use_directory_urls: true
strict: false

markdown_extensions:
  - meta
        
plugins:
  - search
  - rss
  - minify:
      minify_html: true
      
