site_name: Kenny Writes
site_description: The blog of Kenny Robinson, where he shares is hobbies.
site_url: https://almostengr.github.io/
site_author: Kenny Robinson, @almostengr

remote_branch: master
remote_name: origin

theme:
  # name: material
  name: null
  custom_dir: mkdocs-material/material
  language: en
  features: tabs
  palette:
    primary: black
    accent: 'light blue'
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  font:
    text: Ubuntu
    code: Ubuntu Mono
  search_index_only: true
  direction: ltr
  static_templates:
    - 404.html

# repo_url: https://github.com/almostengr
# repo_name: Github
# remote_name: origin

# Copyright
copyright: Copyright &copy; 2015-2020 Kenny Robinson

# Development server details
dev_addr: 192.168.57.117:8000

use_directory_urls: true
strict: false

markdown_extensions:
  - meta
        
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/almostengr
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/almostengr
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/krobinsontech
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/almostengr
