site_name: Kenny Writes
site_description: The blog of Kenny Robinson, where he shares is hobbies and other thoughts.
site_url: https://almostengr.github.io/
site_author: Kenny Robinson, @almostengr

# deployment branch details
remote_branch: master
remote_name: origin

google_analytics: ['UA-64643711-2', 'almostengr.github.io']

theme:
  name: null
  custom_dir: blogalmostengr

copyright: Copyright &copy; 2015-2020 Kenny Robinson

# Development server details
dev_addr: 192.168.57.117:8000

use_directory_urls: true
strict: false

markdown_extensions:
  - meta
        
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/almostengr
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/almostengr
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/krobinsontech
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/almostengr
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC4HCouBLtXD1j1U_17aBqig?sub_confirmation=1
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCB7rvymUaUbbig3skv2zvCQ?sub_confirmation=1

plugins:
  - search
  - minify:
      minify_html: true
      