name: Generate static pages

on:
  push: 
    branches:
      - mkdocs

jobs:
  build:
    name: buildout
    runs-on: ubuntu-latest

    steps:
    - name: Ubuntu, Python, PIP version info
      run: lsb_release -a && python --version && pip --version
      
    - name: Checking out repository
      uses: actions/checkout@v2
      with: 
            repository: almostengr/almostengr.github.io

    - name: Installing python3
      run:  /usr/bin/python3 -m pip install --upgrade pip
    
    - name: Installing setuptools
      run: /usr/bin/python3 -m pip install --upgrade setuptools

    - name: Installing Mkdocs
      run:  /usr/bin/python3 -m pip install mkdocs

    - name: Fetching branches
      run:  git fetch -p

    # - name: Checking out gh-pages branch
    #   run:  git checkout -b gh-pages origin/gh-pages

    - name: Checking out main branch
      run:  git checkout master

    - name: Building static site
      run:  /usr/bin/python3 -m mkdocs gh-deploy
