name: Generate static pages

on:
  push: 
    branches: [ markdown ]
  pull_request:
    branches: [ markdown ]

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Remove duplicates from wordlist
      run: (/bin/cat .wordlist.txt | /usr/bin/sort | /usr/bin/uniq) > .wordlist.tmp
    
    - name: Moving cleaned wordlist
      run: /bin/mv .wordlist.tmp .wordlist.txt
          
    - uses: rojopolis/spellcheck-github-actions@0.5.0
      name: Spellcheck

  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: spelling
    
    steps:
    - name: Installing python3
      run:  /usr/bin/python3 -m pip install --upgrade pip
    
    - name: Installing setuptools
      run: /usr/bin/python3 -m pip install --upgrade setuptools

    - name: Installing Mkdocs
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs

    - name: Install Minify Plugin
      run: /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin
    
    - name: Install RSS Plugin
      run: /usr/bin/python3 -m pip install --upgrade mkdocs-rss-plugin

    - name: Checking out repository
      uses: actions/checkout@v2
      with: 
            repository: almostengr/almostengr.github.io

    - name: Mkdocs Build
      run: /usr/bin/python3 -m mkdocs build
      
    - name: Fetching branches
      run:  git fetch -p

    - name: Building static site
      run:  /usr/bin/python3 -m mkdocs gh-deploy -b master
