name: Generate static pages

on:
  push: 
    branches:
      - mkdocs

jobs:
  build:
    name: buildout
    runs-on: ubuntu-latest

    steps:
    # - name: Ubuntu, Python, Python 3, PIP version info
    #   run: lsb_release -d && python --version && /usr/bin/python3 --version && pip --version
      
    - name: Installing python3
      run:  /usr/bin/python3 -m pip install --upgrade pip
    
    - name: Installing setuptools
      run: /usr/bin/python3 -m pip install --upgrade setuptools

    - name: Installing Mkdocs
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs

    - name: Install Minify Plugin
      run: /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin

    - name: Checking out repository
      uses: actions/checkout@v2
      with: 
            repository: almostengr/almostengr.github.io

    - name: Fetching branches
      run:  git fetch -p

    - name: Building static site
      run:  /usr/bin/python3 -m mkdocs gh-deploy -b master
