name: Generate static pages

on:
  push: 
    branches: [ mkdocs ]
  pull_request:
    branches: [ mkdocs ]

jobs:
  build:
    name: buildout
    runs-on: ubuntu-latest

    steps:      
    - name: Installing python3
      run:  /usr/bin/python3 -m pip install --upgrade pip
    
    - name: Installing setuptools
      run: /usr/bin/python3 -m pip install --upgrade setuptools

    - name: Installing Mkdocs
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs

    - name: Install Minify Plugin
      run: /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin

    - name: Checking out repository
      uses: actions/checkout@v2
      with: 
            repository: almostengr/almostengr.github.io

    - name: Mkdocs Build
      uses: /usr/bin/python3 -m mkdocs build

  spelling:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - uses: rojopolis/spellcheck-github-actions@0.5.0
      name: Spellcheck

    - name: Fetching branches
      run:  git fetch -p

    - name: Building static site
      run:  /usr/bin/python3 -m mkdocs gh-deploy -b master
